### PR TITLE
add msvc12 (VS2013) solution

### PR DESCRIPTION
**Pull request by shearer12345**
this PR adds a msvc12 solution (in a new folder)

- it presently builds, and runs
- [solved], but the Windows message boxes show messages in non-ascii text - presumably a unicode/MBCS issue - see #148 
  - [solved] also creates non-ascii folder names when run - e.g. "㩃啜敳獲猀敨牡牥捜摯履潩㍱扜極摬煜慵敫弳敲敬獡彥慴扜獡煥尳㍱潣普杩挮杦"

### CODE REVIEW

**Comment by shearer12345** [comment]
I believe ready to merge
  - only change to existing files is the .gitignore
  - new files are only Visual Studio files in misc\msvc12\

**Comment by zturtleman** [comment]
Why does this replace the SDL DLLs?

**Comment by shearer12345** [comment]
@zturtleman - I pulled in the dll with the libs, to make sure they matched up
 - from https://www.libsdl.org/download-2.0.php
   - SDL2-devel-2.0.3-VC.zip (Visual C++ 32/64-bit)

Not sure where the present (49ab0cc05e) SDL2.dll is from - it's much larger than any I can find from libsdl.org    But, it does work, so I'm happy to revert to the present version - up to you.

**Comment by zturtleman** [comment]
The SDL DLLs were compiled by @MAN-AT-ARMS. The official 64 bit SDL2 is named SDL2.dll which prevents putting x86 and x86_64 ioquake3 in the same directory. The 64 bit MSVC SDL2.lib would need to be recompiled to use SDL264.dll.

I merged the changes you proposed into the existing msvc10 and msvc11 solutions (which the only difference now is the platform toolset). https://github.com/ioquake/ioq3/compare/49ab0cc05e61...b5e9e1357af5

I'm able to open the solutions in msvc14 (Visual Studio Express 2015) and compile them if I manually put the SDL2 .lib files are in code/libs/win32/. The reason I did not commit the win32 msvc .lib files is that the SDL 2.0.3 ones are not compatible with VS 2015. The ones from the SDL build bot are, so.. 2.0.4 might be compatible. So let's just hold off on that.

I don't really see adding msvc12 that is a copy of msvc11 that VS 2013 auto updated the platform toolset (from `v110` -> `v120`) as very useful when one can just open msvc10 or msvc11 and get the same result. So I'm going to close this. Though, I don't know why msvc11 was added, so maybe others want to comment on whether msvc12 and msvc14 should be added.

Thanks for the improvements.

**Comment by shearer12345** [comment]
sounds good. And useful to know about to VS2015 issues with SDL.

Cheers

**Pull request closed without merging**
