### PR TITLE
SDL_GetCurrentVideoDriver() NULL check

### PR DESCRIPTION
**Pull request by Pan7**
See https://wiki.libsdl.org/SDL_GetCurrentVideoDriver

### CODE REVIEW

**Comment by timangus** [comment]
driverName should never be null if SDL_Init has succeeded.

**Comment by ensiform** [comment]
I think it's more the possibility?  Probably was detected by coverity or some other code analysis.

**Comment by timangus** [comment]
SDL_GetCurrentVideoDriver

"Return Value

Returns the name of the current video driver or NULL if no driver has been initialized."

**Comment by IR4T4** [comment]
r_sdlDriver cvar is set but not used for real. It should be removed and the info of SDL_GetCurrentVideoDriver() output should be added to the /gfxinfo cmd.

**Pull request closed without merging**
