### PR TITLE
Building win64 installers

### PR DESCRIPTION
**Pull request by rmoog**
This should do it.
d2baea6 contains some sed magic I added to the Makefile, so that we can create working nsis scripts.
8bf9aeb contains the script I've been personally using to build the installer. Stuff that is not needed anymore has been commented out.

### CODE REVIEW

**Comment by TimeDoctor** [comment]
There's no way to do this without wine?

**Comment by rmoog** [comment]
Not unless you're building from Windows.

**Comment by timangus** [comment]
This seems odd.

**Comment by zturtleman** [comment]
Creating Win64 installer works using git master on Debian with mingw-w64 and nsis packages installed.

mingw-w64 uses `mingw32` for both x86 and x86_64 so these changes break creating the installer. Debian and Ubuntu (and probably other distros) have makensis available through the package manager (`nsis` package). There is no need for wine.

**Comment by rmoog** [comment]
That explains everything. I was building on Gentoo. Not only nsis is not packaged anymore since time immemorial, but crossdev also does not build makensis as part of the cross-x86_64-pc-mingw32/gcc package.

**Pull request closed without merging**
