### PR TITLE
GLES support and OpenPandora port

### PR DESCRIPTION
**Pull request by ptitSeb**
This version have

GLES support, with the code between #ifdef HAVE_GLES
It should compile with close to no modification on almost all GLES platform

OpenPandora support. There are some tweaking for the Pandora, mainly some Keymapping and Video resolution.

Toggle Crouch support. When playing on joystick, the crouch can be painfull to use, it could be easier with a toggle crouch (#ifdef CROUCH)

Some ARM (#ifdef ARM) and NEON optim (#ifdef NEON)

There are some Hardwired variables in the makefile to activate all that, I haven't found a way to do something better.

### CODE REVIEW

**Comment by TimeDoctor** [comment]
Is the OpenPandora still a thing? I just merged another ARM deal, do we still need that part of this commit?

**Comment by ptitSeb** [comment]
Yes it's still a thing. But that pull request is so old, I better cancel it. PLus, if you now have a GLES renderer, it's fine.

**Comment by ensiform** [comment]
There isn't a gles renderer ludwig nussel's commit was purely a vm_ interface for armv7 arch.

**Comment by ptitSeb** [comment]
But is there still some interrest here to have a GLES renderer?
And if yes, would this be a different renderer or some build options #ifdef in the DesktopGL renderer?

**Comment by ensiform** [comment]
I would imagine a separate renderer is necessary because there are many differences required as GLES is more closely related to modern gl renderer than legacy/vanilla renderer.

**Pull request closed without merging**
