### PR TITLE
Update SDL2 to 2.0.4

### PR DESCRIPTION
**Pull request by MAN-AT-ARMS**

### CODE REVIEW

**Comment by jpcy** [comment]
Why are the binaries, and the ones already in the repo, so much larger than the official SDL2 ones?

The x86 SDL2.dll from SDL2-devel-2.0.4-mingw.tar.gz is 0.99 MB, compared to 4.58 MB here.

**Comment by MAN-AT-ARMS** [comment]
Not sure. Never paid any attention to the size to be honest.
They were cross compiled. Maybe static linking / symbols?
Just compiled from pristine source tarball. I have no idea how the "official" ones were built.

**Comment by TimeDoctor** [comment]
@rcgordon any pro-tips for decreasing the size of our libraries?

**Comment by wtfbbqhax** [comment]
Are they stripped? Do they contain debugging symbols etc?

Run `ldd` on the linux `*.so`- maybe they are static.

**Comment by MAN-AT-ARMS** [comment]
No they weren't stripped which I'm guessing is the reason for the size.

**Comment by rcgordon** [comment]
That'd do it. Is there a reason to not just use the official SDL builds?

**Comment by MAN-AT-ARMS** [comment]
No particular reason other than they are included in the zip file when building a release archive on jenkins. (The 64 bit dll would need to be renamed though.) I put in another PR with stripped dll's.

**Pull request merged**
