### PR TITLE
Use Opus for VoIP [updated]

### PR DESCRIPTION
**Pull request by zturtleman**
Updated #25 to fix merge issues.

### CODE REVIEW

**Comment by TimeDoctor** [comment]
will this cause an incompatibility between older clients and servers and newer? If not, please update and merge.

**Comment by rcgordon** [comment]
To answer zakk's question:

I would generally encourage a switch to Opus (Speex is obsoleted by Opus), but this will cause incompatibilities unless you can get servers and clients to switch over. Namely: old demos with VoIP packets won't play the voices any more (but it's possible no one cares; I thought it was a cool feature but maybe exporting a great demo to YouTube makes more sense at this point anyhow), and servers and clients need to be using the same thing, or no VoIP support.

This approach won't crash, but it probably will cause some headaches. It's possible these headaches aren't a big deal in reality, and in that case you should just rip off the bandaid and ship it and call it a day.

**Comment by zturtleman** [comment]
Rebased commits to fix merge issues. fwiw compatibility with ioq3 1.36 VoIP protocol/playback was dropped in 2011 (ac30d86db01a43130d2c9ff6fe31d6135d8e2592).

**Comment by robo9k** [comment]
This is lacking proper documentation.

Is `libspeex` used at all now? Why is the bundled `code/libspeex/` still there?
Why is `README.md` not matching the updated `Makefile`?
What will happen to the `vcproj` and `xcworkspace`?
The Windows `.nsi` still refers to `libspeex.dll`.
`voip-readme.txt` has not been updated.

**Comment by TimeDoctor** [comment]
Here is how you create a pull request: https://help.github.com/articles/creating-a-pull-request/

**Pull request merged**
