### PR TITLE
Additional updates to the Xcode project

### PR DESCRIPTION
**Pull request by tomkidd**
So, basically the gig is this:

The Xcode project, which as near as I can tell hadn't been updated since 2013 prior to my updates over the weekend, handles the generation of the GLSL C files via a Run Script phase (sort of the equivalent of the pre-/post-build steps in Visual Studio). It would run the script to generate the .c files, then run the Compile Sources phase, then run another Run Script phase to delete the .c files. 

Consequently, when you load the project up in Xcode it would show the glsl/*.c files as missing but this is normal since the phases were set to generate them in time and then delete them immediately. 

My guess is that some time between Xcode 4 and Xcode 11 this behavior changed. As in, for some reason Xcode will run the script to generate the .c files, but then the Compile Sources step fails because the files didn't exist prior to that phase executing. But if you try it again it works because those .c files now exist because the previous build stopped before the second phase that deletes them could run. 

So the process was something like this

First build:
1. glsl/*.c files don't exist
2. "Generate C From GLSL Files" Run Phase generates the glsl/*.c files
3. Compile Sources phase fails because glsl/*.c files didn't exist when the build started
4. Exit with error

Second build:
1. glsl/*.c files do exist because they were generated by previous build and not deleted
2. "Generate C From GLSL Files" Run Phase generates the glsl/*.c files (they already existed, but they get regenerated anyway)
3. Compile Sources phase succeeds because glsl/*.c files did exist when the process started
4. "Delete GLSL-Generated C Files" Run Phase deletes the glsl/*.c files

And consequently the next build will behave like the first build above, the subsequent build will behave like the second build above, etc. Every other build succeeds. 

So what I've done here to lessen the impact is the following

a) Removed the second "Delete" Run Script phase. It doesn't matter if the files exist, the process will overwrite them

b) Added code/renderergl2/glsl/*.c to .gitignore. This way the generated .c files can't accidentally get added to source control. 

It still means the first build will fail, and I've modified the Xcode readme text file to reflect this, but until or unless I can come up with a better idea this at least limits the impact for anyone wanting to use Xcode to debug something. I also took the liberty of updating the xcode-readme.txt file to reflect the updates.

But since this change modifies .gitignore I figure a PR might be the best way to handle it.

### CODE REVIEW

**Comment by zturtleman** [comment]
It would be nice if the Xcode project created `glsl/*.c` in the build directory like the Makefile and [Visual Studio projects](https://github.com/ioquake/ioq3/blob/daae32ddfdab2172a628072ed3ff7dd1fc1563fe/misc/msvc12/opengl2.vcxproj#L97) (no change needed to .gitignore).

If it's inconvenient / not possible for Xcode then adding a line to .gitignore is probably fine. It might be worth adding a comment to .gitignore that it's for the Xcode project.

**Comment by tomkidd** [comment]
I’ll take a look and see.

**Comment by tomkidd** [comment]
OK, I was able to modify the generation script step to put it in a `/build/dynamic/renderergl2` folder similar to the Makefile and Visual Studio files. It still has the issue of the first build failing but it no longer needs a `.gitignore` change

**Comment by zturtleman** [comment]
Okay, thanks. It seems fine to merge to me.

**Pull request merged**
